openapi: '3.0.2'

info:
  title: peruservice-scheduler
  version: 1.0.0

servers:
  - url: http://localhost:3015

tags:
    - name: utility
      description: 各種機能のAPI
    - name: scheduler
      description: スケジュールを管理するAPI
paths:
  /:
    get:
      tags:
        - utility
      summary: 接続を確認する
      responses:
        '200':
          description: OK
  /schedule:
    post:
      tags:
        - scheduler
      summary: スケジュールを登録する
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostScheduleRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleID'
      security:
        - Bearer: []
  /schedules:
    get:
      tags:
        - scheduler
      summary: スケジュール一覧を取得する
      parameters:
        - name: startDate
          in: query
          required: true
          description: 指定期間の開始日時
          schema:
            type: string
        - name: endDate
          in: query
          required: true
          description: 指定期間の終了日時
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetScheduleListResponse'
      security:
        - Bearer: []
  /schedule/{scheduleID}:
    get:
      tags:
        - scheduler
      summary: スケジュールを取得する
      parameters:
        - name: scheduleID
          in: path
          required: true
          description: スケジュールID
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetScheduleResponse'
      security:
        - Bearer: []
    put:
      tags:
        - scheduler
      summary: スケジュールを更新する
      parameters:
        - name: scheduleID
          in: path
          required: true
          description: スケジュールID
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutScheduleRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleID'
      security:
        - Bearer: []
    delete:
      tags:
        - scheduler
      summary: スケジュールを削除する
      parameters:
        - name: scheduleID
          in: path
          required: true
          description: スケジュールID
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleID'
      security:
        - Bearer: []
          
components:
  schemas:
    ScheduleID:
      type: object
      properties:
        scheduleID:
          type: string
          description: スケジュールID
    GetScheduleListResponse:
      type: object
      properties:
        scheduleList:
          type: array
          items:
            $ref: '#/components/schemas/GetScheduleResponse'
    GetScheduleResponse:
      type: object
      properties:
        scheduleID:
          type: string
          description: スケジュールID
          example: "qwertyuiopasdfghjklzxcvbnm"
        title:
          type: string
          description: スケジュールタイトル
          example: "バカンス"
        description:
          type: string
          description: スケジュール詳細
          example: "バカンスです"
        startDate:
          type: string
          description: 開始日時
          example: "2023-08-07T01:00:00.000Z"
        endDate:
          type: string
          description: 終了日時
          example: "2023-08-07T02:00:00.000Z"
        allday:
          type: boolean
          description: 終日フラグ
          example: false
        tags:
          type: array
          items:
            type: string
          description: タグ
          example: ["個人", "休暇"]
        properties:
          type: array
          items:
            type: string
          description: プロパティ
          example: ["dayFlexible", "notImportant"]
        isPublic:
          type: boolean
          description: 公開フラグ
          example: false
        createdAt:
          type: string
          description: 作成日時
          example: "2023-08-05T01:00:00.000Z"
        updatedAt:
          type: string
          description: 更新日時
          example: "2023-08-05T01:00:00.000Z"
    PostScheduleRequest:
      type: object
      properties:
        title:
          type: string
          description: スケジュールタイトル
          example: "バカンス"
        description:
          type: string
          description: スケジュール詳細
          example: "バカンスです"
        startDate:
          type: string
          description: 開始日時
          example: "2023-08-07T01:00:00.000Z"
        endDate:
          type: string
          description: 終了日時
          example: "2023-08-07T02:00:00.000Z"
        allday:
          type: boolean
          description: 終日フラグ
          example: false
        tags:
          type: array
          items:
            type: string
          description: タグ
          example: ["個人", "休暇"]
        properties:
          type: array
          items:
            type: string
          description: プロパティ
          example: ["dayFlexible", "notImportant"]
        isPublic:
          type: boolean
          description: 公開フラグ
          example: false
    PutScheduleRequest:
      type: object
      properties:
        title:
          type: string
          description: スケジュールタイトル
          example: "バカンス"
        description:
          type: string
          description: スケジュール詳細
          example: "バカンスです"
        startDate:
          type: string
          description: 開始日時
          example: "2023-08-07T01:00:00.000Z"
        endDate:
          type: string
          description: 終了日時
          example: "2023-08-07T02:00:00.000Z"
        allday:
          type: boolean
          description: 終日フラグ
          example: false
        tags:
          type: array
          items:
            type: string
          description: タグ
          example: ["個人", "休暇"]
        properties:
          type: array
          items:
            type: string
          description: プロパティ
          example: ["dayFlexible", "notImportant"]
        isPublic:
          type: boolean
          description: 公開フラグ
          example: false

  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      description: JWTアクセストークン